#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-hoe-highline
Version  : 0.2.1
Release  : 5
URL      : https://rubygems.org/downloads/hoe-highline-0.2.1.gem
Source0  : https://rubygems.org/downloads/hoe-highline-0.2.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
BuildRequires : ruby
BuildRequires : rubygem-highline
BuildRequires : rubygem-hoe
BuildRequires : rubygem-minitest
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-test-unit

%description
= hoe-highline
* https://bitbucket.org/ged/hoe-highline
* https://github.com/ged/hoe-highline

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n hoe-highline-0.2.1
gem spec %{SOURCE0} -l --ruby > rubygem-hoe-highline.gemspec

%build
gem build rubygem-hoe-highline.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
hoe-highline-0.2.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/hoe-highline-0.2.1
rake --trace test TESTOPTS="-v"
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/hoe-highline-0.2.1.gem
/usr/lib64/ruby/gems/2.2.0/doc/hoe-highline-0.2.1/ri/Hoe/Highline/cdesc-Highline.ri
/usr/lib64/ruby/gems/2.2.0/doc/hoe-highline-0.2.1/ri/Hoe/Highline/define_highline_tasks-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hoe-highline-0.2.1/ri/Hoe/Highline/highline-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hoe-highline-0.2.1/ri/Hoe/Highline/initialize_highline-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hoe-highline-0.2.1/ri/Hoe/cdesc-Hoe.ri
/usr/lib64/ruby/gems/2.2.0/doc/hoe-highline-0.2.1/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/hoe-highline-0.2.1/ri/page-History_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/doc/hoe-highline-0.2.1/ri/page-Manifest_txt.ri
/usr/lib64/ruby/gems/2.2.0/doc/hoe-highline-0.2.1/ri/page-README_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/gems/hoe-highline-0.2.1/ChangeLog
/usr/lib64/ruby/gems/2.2.0/gems/hoe-highline-0.2.1/History.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/hoe-highline-0.2.1/Manifest.txt
/usr/lib64/ruby/gems/2.2.0/gems/hoe-highline-0.2.1/README.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/hoe-highline-0.2.1/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/hoe-highline-0.2.1/lib/hoe/highline.rb
/usr/lib64/ruby/gems/2.2.0/specifications/hoe-highline-0.2.1.gemspec
